print('Enter the name of ca1 1:')
catName1 = input()
print('Enter the name of ca1 2:')
catName2 = input()
print('Enter the name of ca1 3:')
catName3 = input()
print('Enter the name of ca1 4:')
catName4 = input()
print('Enter the name of ca1 5:')
catName5 = input()
print('Enter the name of ca1 6:')
catName6 = input()

print(catName1 + ' ' + catName2 ' ' + catName3 + ' ' + catName4 ' ' + catName5 + ' ' + catName6 + ' ')